apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
    - name: html-generator
      image: luksa/fortune:latest
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - name: webserver
      image: nginx:alpine
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: html
      emptyDir: {}
