apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
    - image: nginx:alpine
      name: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: log
          mountPath: /var/log/nginx
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: html
      gitRepo:
        repository: https://github.com/htnicayh/example.git
        revision: master
        directory: . # Clone into the root dir of the volume
    - name: log
      hostPath:
        path: /var/log # Folder of worker node