apiVersion: v1
kind: Service
metadata:
  name: statefulset
spec:
  clusterIP: None
  selector:
    app: statefulset
  ports:
    - name: http
      port: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: statefulset
  serviceName: statefulset
  replicas: 2
  template:
    metadata:
      labels:
        app: statefulset
    spec:
      containers:
        - name: statefulset
          image: 130620/k8s-statefulsets:latest
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /var/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 1Mi
        accessModes:
          - ReadWriteOnce
