apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-rc
spec:
  replicas: 2
  selector:
    app: kube-rc-pod
  template:
    metadata:
      labels:
        app: kube-rc-pod
    spec:
      containers:
      - name: kube-rc-container
        image: 130620/k8s-pod:latest
        ports:
        - containerPort: 3000