apiVersion: v1
kind: Pod
metadata:
  name: pod-test-pvcs
spec:
  containers:
    - name: mongo
      image: mongodb
      ports:
        - containerPort: 27017
          protocol: TCP
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: persistent-volume-claim