apiVersion: v1
kind: Pod
metadata:
  name: pod-with-cm
spec:
  containers:
    - image: 130620/k8s-cm:latest
      name: pod-with-cm
      ports:
        - containerPort: 3000
      envFrom:
        - configMapRef:
            name: pg-config