apiVersion: v1
kind: Pod
metadata:
  name: k8s-pod
  labels:
    app: hyacinth
    environment: development
    tier: backend
    version: v1
    owner: k8s
    team: devops
spec:
  containers:
  - name: k8s-container
    image: 130620/k8s-pod:latest
    ports:
    - containerPort: 3000
      protocol: TCP